// geoserves-pelagos-design-system-main/components/primitives/button/Button.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  OnChanges,
  SimpleChanges,
  isDevMode,
} from '@angular/core';
import { CommonModule }      from '@angular/common';
import { NzButtonModule }    from 'ng-zorro-antd/button';
import { NzConfigService }   from 'ng-zorro-antd/core/config';
import { getButtonTheme }    from './buttonTheme';

/**
 * Pelagos Button — Angular wrapper
 * primitives/button/Button.component.ts
 *
 * A thin Pelagos wrapper on top of ng-zorro-antd's nz-button directive.
 * All interactive behaviours (loading, disabled, keyboard, a11y) are
 * delegated to ng-zorro. Pelagos design tokens are applied via NZ_CONFIG
 * at module/bootstrap level — see README.md "Angular: Applying Pelagos Tokens".
 *
 * This is a standalone component (Angular 15+). NgModule apps should use
 * ButtonModule instead, which re-exports ButtonComponent for backward compat.
 *
 * ─── Input mapping ──────────────────────────────────────────────────────────
 *
 *   Pelagos @Input  │ ng-zorro equivalent          │ Notes
 *   ────────────────┼──────────────────────────────┼──────────────────────────
 *   variant         │ nzType + nzDanger            │ see VARIANT_MAP below
 *   size            │ nzSize                       │ sm→small  md→default  lg→large
 *   fullWidth       │ nzBlock                      │ replaces nzBlock
 *   loading         │ nzLoading                    │
 *   disabled        │ [disabled]                   │ native HTML attr
 *   ghost           │ nzGhost                      │ passed through
 *   shape           │ nzShape                      │ 'circle' | 'round' | 'default'
 *   type            │ [attr.type]                  │ HTML button type: submit/reset/button
 *   href            │ href (renders <a>)           │ ng-zorro handles link rendering
 *   target          │ target                       │ used with href
 *
 * ─── Migration from raw ng-zorro ────────────────────────────────────────────
 *
 *   ng-zorro usage               │ Pelagos equivalent
 *   ─────────────────────────────┼──────────────────────────────────────────
 *   nzType="primary"             │ variant="primary"
 *   nzType="default"             │ variant="secondary"
 *   nzType="text"                │ variant="tertiary"
 *   nzType="link"                │ variant="link"
 *   nzType="primary" nzDanger    │ variant="danger"
 *   nzType="default" nzDanger    │ variant="danger-secondary"
 *   nzSize="large"               │ size="lg"
 *   nzSize="default"             │ size="md"
 *   nzSize="small"               │ size="sm"
 *   nzBlock                      │ fullWidth
 *   nzLoading / disabled / nzGhost / nzShape
 *                                │ unchanged — same @Input names
 *
 * ─── Design tokens ──────────────────────────────────────────────────────────
 *
 * Tokens come from buttonTheme.js (shared with React). Inject them at the
 * module level using NZ_CONFIG or provide them via NzConfigService in your
 * AppModule / standalone bootstrap to avoid polluting the global theme.
 *
 * ─── Design reference ───────────────────────────────────────────────────────
 * /pages/prim-buttons.html
 */

// ─── Variant → ng-zorro nzType + nzDanger ────────────────────────────────────

const VARIANT_MAP: Record<string, { nzType: string; nzDanger: boolean }> = {
  primary:            { nzType: 'primary', nzDanger: false },
  secondary:          { nzType: 'default', nzDanger: false },
  tertiary:           { nzType: 'text',    nzDanger: false },
  danger:             { nzType: 'primary', nzDanger: true  },
  'danger-secondary': { nzType: 'default', nzDanger: true  },
  neutral:            { nzType: 'default', nzDanger: false },
  link:               { nzType: 'link',    nzDanger: false },
};

// ─── Size → ng-zorro nzSize ──────────────────────────────────────────────────

const SIZE_MAP: Record<string, string> = {
  sm: 'small',
  md: 'default',
  lg: 'large',
};

@Component({
  selector:     'gs-button',
  standalone:   true,
  imports:      [CommonModule, NzButtonModule],
  templateUrl:  './Button.component.html',
  host:         { class: 'gs-button-host' },
})
export class ButtonComponent implements OnChanges {

  constructor(private nzConfigService: NzConfigService) {}

  // ── Pelagos props ──────────────────────────────────────────────────────────

  /** Visual style. Maps to ng-zorro nzType + nzDanger. @default 'primary' */
  @Input() variant: string = 'primary';

  /** Size token. Maps to ng-zorro nzSize. @default 'md' */
  @Input() size: 'sm' | 'md' | 'lg' = 'md';

  /** Stretch to container width. Maps to ng-zorro nzBlock. @default false */
  @Input() fullWidth: boolean = false;

  // ── Props forwarded directly to ng-zorro ──────────────────────────────────

  /** Show loading spinner. */
  @Input() loading: boolean = false;

  /** Disable the button. */
  @Input() disabled: boolean = false;

  /** Transparent background for coloured surfaces. */
  @Input() ghost: boolean = false;

  /** Button shape: 'default' | 'circle' | 'round'. */
  @Input() shape: 'default' | 'circle' | 'round' = 'default';

  /** HTML button type attribute. @default 'button' */
  @Input() type: 'button' | 'submit' | 'reset' = 'button';

  /** Renders an <a> tag when set. */
  @Input() href?: string;

  /** Link target — used with href. */
  @Input() target?: string;

  /**
   * @deprecated Not supported. Use `variant` instead.
   * Intercepted to mirror React's `color` prop guard and prevent accidental
   * passthrough of the AntD v5.13+ `color` input.
   */
  @Input() color?: string;

  // ── Events ────────────────────────────────────────────────────────────────

  /** Click event (delegated from nz-button). */
  @Output() clicked = new EventEmitter<MouseEvent>();

  // ── Derived ng-zorro binding values (computed on change) ─────────────────

  nzType: string    = 'primary';
  nzDanger: boolean = false;
  nzSize: string    = 'default';

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['variant']) {
      const mapped = VARIANT_MAP[this.variant] ?? VARIANT_MAP['primary'];
      this.nzType   = mapped.nzType;
      this.nzDanger = mapped.nzDanger;

      // ── Per-variant token injection ──────────────────────────────────────
      // React uses a scoped ConfigProvider; ng-zorro exposes NzConfigService
      // for the same purpose. We extract the Button component tokens from the
      // shared buttonTheme.js and push them into the service so this instance
      // renders identically to its React counterpart.
      //
      // NzConfigService.set() is scoped to the service instance injected into
      // this component — it does NOT mutate the global NZ_CONFIG token.
      const theme = getButtonTheme(this.variant);
      const buttonTokens = theme?.components?.['Button'];
      if (buttonTokens) {
        this.nzConfigService.set('button', {
          nzSize: (SIZE_MAP[this.size] ?? 'default') as any,
          ...buttonTokens,
        });
      }

    }
    if (changes['size']) {
      this.nzSize = SIZE_MAP[this.size] ?? 'default';
    }
    if (isDevMode() && changes['color'] && this.color !== undefined) {
      console.warn(
        '[PelagosButton] The `color` input is not supported. Use `variant` instead.',
      );
    }
  }

  handleClick(event: MouseEvent): void {
    this.clicked.emit(event);
  }
}

<!--
  Pelagos Button — Angular template
  primitives/button/Button.component.html

  Delegates all rendering and behaviour to ng-zorro's nz-button directive.
  Pelagos props are translated to ng-zorro bindings in ButtonComponent.ts.

  Single-icon (left or right): use the iconLeft / iconRight content slots.
  Dual-icon fallback: include both slots; structural spans handle the gap.
-->

<!-- ── Link button (href present) ─────────────────────────────────────────── -->
<ng-container *ngIf="href; else regularButton">
  <a
    nz-button
    [nzType]="nzType"
    [nzDanger]="nzDanger"
    [nzSize]="nzSize"
    [nzBlock]="fullWidth"
    [nzLoading]="loading"
    [nzGhost]="ghost"
    [nzShape]="shape"
    [href]="href"
    [target]="target"
    [attr.disabled]="disabled ? true : null"
    [attr.data-variant]="variant"
    (click)="handleClick($event)"
  >
    <ng-container *ngTemplateOutlet="buttonContent"></ng-container>
  </a>
</ng-container>

<!-- ── Regular button ─────────────────────────────────────────────────────── -->
<ng-template #regularButton>
  <button
    nz-button
    [nzType]="nzType"
    [nzDanger]="nzDanger"
    [nzSize]="nzSize"
    [nzBlock]="fullWidth"
    [nzLoading]="loading"
    [nzGhost]="ghost"
    [nzShape]="shape"
    [disabled]="disabled"
    [type]="type"
    [attr.data-variant]="variant"
    (click)="handleClick($event)"
  >
    <ng-container *ngTemplateOutlet="buttonContent"></ng-container>
  </button>
</ng-template>

<!-- ── Shared content projection ──────────────────────────────────────────── -->
<ng-template #buttonContent>
  <ng-content select="[iconLeft]"></ng-content>
  <ng-content></ng-content>
  <ng-content select="[iconRight]"></ng-content>
</ng-template>

// geoserves-pelagos-design-system-main/components/primitives/button/Button.jsx
import React from 'react';
import { Button as AntButton, ConfigProvider } from 'antd';
import { getButtonTheme } from './buttonTheme';
import './Button.scss';

/**
 * Pelagos Button — primitives/button
 *
 * A thin Pelagos wrapper on top of Ant Design's Button component.
 *
 * All interactive behaviours — loading spinner, wave-ripple click feedback,
 * keyboard activation, disabled state, aria attributes, and link rendering
 * (via href) — are delegated entirely to AntD. Pelagos design tokens are
 * injected via a scoped ConfigProvider so they never bleed into the global
 * application theme.
 *
 * Refs are forwarded to the underlying AntD Button, preserving compatibility
 * with form libraries (react-hook-form, Formik), focus management, and any
 * existing ref usage in the consuming app.
 *
 * ─── Prop mapping ───────────────────────────────────────────────────────────
 *
 *   Pelagos prop   │ AntD equivalent             │ Notes
 *   ───────────────┼─────────────────────────────┼───────────────────────────
 *   variant        │ type + danger               │ see VARIANT_MAP below
 *   size           │ size                        │ sm→small  md→middle  lg→large
 *   fullWidth      │ block                       │ replaces AntD `block`
 *   iconLeft       │ icon + iconPosition="start" │ AntD handles gap + alignment
 *   iconRight      │ icon + iconPosition="end"   │ AntD handles gap + alignment
 *   type           │ htmlType                    │ HTML button type: submit/reset/button
 *   loading        │ loading                     │ boolean OR { delay: number }
 *   disabled       │ disabled                    │
 *   onClick        │ onClick                     │
 *
 * ─── AntD passthrough ───────────────────────────────────────────────────────
 *
 * All other Ant Design Button props (href, target, shape, ghost, classNames,
 * styles, etc.) pass through via ...rest unchanged:
 * https://ant.design/components/button#api
 *
 * ─── AntD version notes ─────────────────────────────────────────────────────
 *
 * v5.13+: AntD introduced its own `variant` prop (outlined/solid/filled/…) and
 * a `color` prop. Both are intercepted here: `variant` is consumed by Pelagos
 * and translated via VARIANT_MAP; `color` is destructured and dropped to
 * prevent conflicting passthrough. Use Pelagos `variant` for all visual style.
 *
 * v5.17+: `iconPosition` prop added — required for iconLeft/iconRight to work.
 * Peer dependency is set to antd >= 5.17.0 for this reason.
 *
 * ─── Migration from raw AntD ────────────────────────────────────────────────
 *
 *   AntD usage                     │ Pelagos equivalent
 *   ───────────────────────────────┼────────────────────────────────────────
 *   type="primary"                 │ variant="primary"
 *   type="default"                 │ variant="secondary"
 *   type="text"                    │ variant="tertiary"
 *   type="link"                    │ variant="link"
 *   type="primary" danger={true}   │ variant="danger"
 *   type="default" danger={true}   │ variant="danger-secondary"
 *   size="large"                   │ size="lg"
 *   size="middle"                  │ size="md"
 *   size="small"                   │ size="sm"
 *   block={true}                   │ fullWidth={true}
 *   ref={myRef}                    │ ref={myRef}  (forwarded — no change needed)
 *   loading / disabled / href / target / shape / ghost / onClick
 *                                  │ unchanged — pass through via ...rest
 *
 * ─── Design tokens ──────────────────────────────────────────────────────────
 *
 * Token overrides live in buttonTheme.js. No CSS variables or custom classes
 * are used for colour — every shade is driven by AntD's token system via a
 * scoped ConfigProvider.
 *
 * ─── Design reference ───────────────────────────────────────────────────────
 * /pages/prim-buttons.html
 */

// ─── Variant → AntD type + danger flag ───────────────────────────────────────

const VARIANT_MAP = {
  primary:            { type: 'primary', danger: false },
  secondary:          { type: 'default', danger: false },
  tertiary:           { type: 'text',    danger: false },
  danger:             { type: 'primary', danger: true  },
  'danger-secondary': { type: 'default', danger: true  },
  neutral:            { type: 'default', danger: false },
  link:               { type: 'link',    danger: false },
};

// ─── Size → AntD size ────────────────────────────────────────────────────────

const SIZE_MAP = {
  sm: 'small',
  md: 'middle',
  lg: 'large',
};

// ─── Variants that require a scoped ConfigProvider for per-variant token overrides.
// primary, danger, and link are fully covered by PelagosProvider at the app root
// and must NOT be wrapped — doing so would add an unnecessary React tree node
// and could mask future root-level token changes.

const THEMED_VARIANTS = new Set(['secondary', 'tertiary', 'neutral', 'danger-secondary']);

// ─── Component ───────────────────────────────────────────────────────────────

export const Button = React.forwardRef(function Button(
  {
    // ── Pelagos-specific props ───────────────────────────────────────────────
    variant   = 'primary',
    size      = 'md',
    iconLeft,
    iconRight,
    fullWidth = false,
    type      = 'button',   // HTML button type (submit | reset | button) → htmlType

    // ── Intercepted to prevent AntD v5.13+ passthrough conflicts ────────────
    color,                  // eslint-disable-line no-unused-vars  (AntD v5.13+)

    // ── Props forwarded to AntD Button ──────────────────────────────────────
    disabled  = false,
    loading   = false,      // boolean | { delay: number }
    onClick,
    children,
    className,
    ...rest                 // all other AntD Button props: href, target, shape, ghost, …
  },
  ref,
) {
  const { type: antType, danger } = VARIANT_MAP[variant] ?? VARIANT_MAP.primary;
  const antSize                   = SIZE_MAP[size]        ?? 'middle';

  // ── Dev-mode prop guard ──────────────────────────────────────────────────
  if (process.env.NODE_ENV !== 'production' && color !== undefined) {
    console.warn('[PelagosButton] The `color` prop is not supported. Use `variant` instead.');
  }

  // ── Icon handling ────────────────────────────────────────────────────────
  //
  // AntD Button supports one `icon` node with an `iconPosition` ("start"|"end").
  // When only one icon is provided we pass it to AntD so it handles the gap,
  // alignment, and icon-only sizing automatically.
  //
  // When BOTH iconLeft and iconRight are provided we fall back to manual markup
  // (spans with margin only; AntD still renders the button shell).

  const hasBothIcons = Boolean(iconLeft && iconRight);
  let   icon, iconPosition;

  if (!hasBothIcons) {
    if (iconLeft)  { icon = iconLeft;  iconPosition = 'start'; }
    if (iconRight) { icon = iconRight; iconPosition = 'end';   }
  }

  const buttonNode = (
    <AntButton
      ref={ref}
      type={antType}
      danger={danger}
      size={antSize}
      disabled={disabled}
      loading={loading}
      block={fullWidth}
      icon={icon}
      iconPosition={iconPosition}
      htmlType={type}
      onClick={onClick}
      className={className}
      data-variant={variant}
      {...rest}
    >
      {hasBothIcons ? (
        <>
          <span className="btn__icon--left">{iconLeft}</span>
          {children}
          <span className="btn__icon--right">{iconRight}</span>
        </>
      ) : children}
    </AntButton>
  );

  // primary, danger, and link are covered by PelagosProvider at the app root —
  // skip the ConfigProvider entirely for those variants.
  if (!THEMED_VARIANTS.has(variant)) {
    return buttonNode;
  }

  return (
    <ConfigProvider theme={getButtonTheme(variant)}>
      {buttonNode}
    </ConfigProvider>
  );
});

Button.displayName = 'PelagosButton';

export default Button;
