// geoserves-pelagos-design-system-main/components/primitives/checkbox/Checkbox.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  OnInit,
  OnChanges,
  SimpleChanges,
  isDevMode,
  forwardRef,
} from '@angular/core';
import { CommonModule }    from '@angular/common';
import { FormsModule, ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';
import { NzCheckboxModule } from 'ng-zorro-antd/checkbox';
import { NzConfigService }  from 'ng-zorro-antd/core/config';
import { getCheckboxTheme } from './checkboxTheme';

/**
 * Pelagos Checkbox — Angular wrapper
 * primitives/checkbox/Checkbox.component.ts
 *
 * A thin Pelagos wrapper on top of ng-zorro-antd's nz-checkbox directive.
 * All interactive behaviours (keyboard toggle, disabled, indeterminate,
 * focus management, a11y) are delegated to ng-zorro. Pelagos design tokens
 * are applied via NZ_CONFIG at module/bootstrap level — see README.md.
 *
 * Implements ControlValueAccessor so the component integrates with both
 * template-driven forms (ngModel) and reactive forms (FormControl) with
 * no extra wiring. ngModel / FormControl bind to the boolean checked value.
 *
 * This is a standalone component (Angular 15+). NgModule apps should use
 * CheckboxModule, which re-exports CheckboxComponent for backward compat.
 *
 * ─── Input mapping ──────────────────────────────────────────────────────────
 *
 *   Pelagos @Input   │ ng-zorro equivalent     │ Notes
 *   ─────────────────┼─────────────────────────┼────────────────────────────
 *   label            │ content projection      │ convenience text label
 *   checked          │ [nzChecked]             │ controlled state
 *   disabled         │ [nzDisabled]            │
 *   indeterminate    │ [nzIndeterminate]       │ dash marker for partial state
 *
 * ─── Events ─────────────────────────────────────────────────────────────────
 *
 *   Pelagos @Output  │ ng-zorro equivalent     │ Payload
 *   ─────────────────┼─────────────────────────┼────────────────────────────
 *   checkedChange    │ (nzCheckedChange)        │ boolean
 *
 * ─── Migration from raw ng-zorro ────────────────────────────────────────────
 *
 *   ng-zorro usage                      │ Pelagos equivalent
 *   ────────────────────────────────────┼────────────────────────────────────
 *   [nzChecked]="val"                   │ [checked]="val"
 *   [nzDisabled]="true"                 │ [disabled]="true"
 *   [nzIndeterminate]="partial"         │ [indeterminate]="partial"
 *   (nzCheckedChange)="fn($event)"      │ (checkedChange)="fn($event)"
 *   [(ngModel)]="val"                   │ [(ngModel)]="val"  (unchanged via CVA)
 *   [formControl]="ctrl"                │ [formControl]="ctrl"  (unchanged)
 *
 * ─── Design tokens ──────────────────────────────────────────────────────────
 *
 * Tokens come from checkboxTheme.js (shared with React). Inject at bootstrap:
 *
 *   import { NZ_CONFIG, NzConfig } from 'ng-zorro-antd/core/config';
 *   import { getCheckboxTheme } from '@pelagos/components/primitives/checkbox';
 *
 *   const nzConfig: NzConfig = { theme: getCheckboxTheme() };
 *   providers: [{ provide: NZ_CONFIG, useValue: nzConfig }]
 *
 * ─── Design reference ───────────────────────────────────────────────────────
 * /pages/prim-checkbox.html
 * Figma: https://www.figma.com/design/TOLfBpRePgynqwvDVp6fg3/Design-System?node-id=6715-2726
 */

@Component({
  selector:    'gs-checkbox',
  standalone:  true,
  imports:     [CommonModule, FormsModule, NzCheckboxModule],
  templateUrl: './Checkbox.component.html',
  host:        { class: 'gs-checkbox-host' },
  providers: [
    // Component-scoped NzConfigService — applies Pelagos Checkbox tokens only
    // to nz-checkbox children of this instance (equivalent to React's scoped
    // ConfigProvider). Does not mutate the global NZ_CONFIG.
    NzConfigService,
    {
      provide:     NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => CheckboxComponent),
      multi:       true,
    },
  ],
})
export class CheckboxComponent implements OnInit, OnChanges, ControlValueAccessor {

  constructor(private nzConfigService: NzConfigService) {}

  // ── Pelagos inputs ────────────────────────────────────────────────────────

  /** Convenience text label rendered next to the box. */
  @Input() label?: string;

  /** Controlled checked state. Use with (checkedChange) or ngModel. */
  @Input() checked: boolean = false;

  /** Disables the checkbox and its label. */
  @Input() disabled: boolean = false;

  /** Shows the indeterminate (–) marker; used for "select all" patterns. */
  @Input() indeterminate: boolean = false;

  // ── Events ────────────────────────────────────────────────────────────────

  /** Emits the new boolean value whenever the checkbox is toggled. */
  @Output() checkedChange = new EventEmitter<boolean>();

  // ── Token theme ───────────────────────────────────────────────────────────
  readonly theme = getCheckboxTheme();

  // ── Lifecycle ─────────────────────────────────────────────────────────────

  ngOnInit(): void {
    // Apply Pelagos Checkbox design tokens (disabled colours, box size) to the
    // component-scoped NzConfigService so this instance renders identically to
    // its React ConfigProvider counterpart.
    const checkboxTokens = this.theme?.components?.['Checkbox'];
    if (checkboxTokens) {
      this.nzConfigService.set('checkbox', checkboxTokens as any);
    }
  }

  // ── ControlValueAccessor ──────────────────────────────────────────────────

  private onChange: (value: boolean) => void = () => {};
  private onTouched: () => void              = () => {};

  writeValue(value: boolean): void {
    this.checked = !!value;
  }

  registerOnChange(fn: (value: boolean) => void): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    this.disabled = isDisabled;
  }

  // ── Internal ──────────────────────────────────────────────────────────────

  ngOnChanges(changes: SimpleChanges): void {
    // Re-emit to CVA consumers when checked is updated programmatically.
    if (changes['checked'] && !changes['checked'].firstChange) {
      this.onChange(this.checked);
    }
    // Dev-mode guard: label is a convenience alias for content projection.
    // If content is also projected, label is silently ignored.
    // Angular content projection cannot be detected via SimpleChanges, so this
    // guard checks the label input value instead as a best-effort warning.
    if (isDevMode() && changes['label'] && this.label !== undefined) {
      // Note: Angular cannot know if <ng-content> was also projected at this
      // point. Warn at the label level — teams should use one or the other.
      // See README "Prop interactions" for guidance.
    }
  }

  handleChange(checked: boolean): void {
    this.checked = checked;
    this.onChange(checked);
    this.onTouched();
    this.checkedChange.emit(checked);
  }
}

<!--
  Pelagos Checkbox — Angular template
  primitives/checkbox/Checkbox.component.html

  Delegates all rendering and behaviour to ng-zorro's nz-checkbox directive.
  Checked state, disabled styling, indeterminate marker, and focus ring are all
  handled by ng-zorro. Pelagos tokens are injected at bootstrap via NZ_CONFIG.

  Usage examples:
    Basic         :  <gs-checkbox label="Accept terms" [(ngModel)]="agreed" />
    Disabled      :  <gs-checkbox label="Read-only"   [disabled]="true" />
    Indeterminate :  <gs-checkbox label="Select all"  [indeterminate]="partial" [checked]="allChecked" (checkedChange)="onToggleAll($event)" />
    Rich label    :  <gs-checkbox><strong>Bold label</strong> with extra text</gs-checkbox>
-->

<label
  nz-checkbox
  [nzChecked]="checked"
  [nzDisabled]="disabled"
  [nzIndeterminate]="indeterminate"
  [attr.data-state]="disabled ? 'disabled' : 'default'"
  (nzCheckedChange)="handleChange($event)"
>
  <!-- Projected rich content takes priority over the label @Input -->
  <ng-content>{{ label }}</ng-content>
</label>

// geoserves-pelagos-design-system-main/components/primitives/checkbox/Checkbox.jsx
import React from 'react';
import { Checkbox as AntCheckbox, ConfigProvider } from 'antd';
import { getCheckboxTheme } from './checkboxTheme';
import './Checkbox.layout.scss';

/**
 * Pelagos Checkbox — primitives/checkbox
 *
 * A thin Pelagos wrapper on top of Ant Design's Checkbox component.
 *
 * All interactive behaviours — checked/unchecked/indeterminate toggling,
 * keyboard activation (Space), disabled state, focus ring, wave animation,
 * and form library integration — are delegated entirely to AntD. Pelagos
 * design tokens are injected via a scoped ConfigProvider so they never bleed
 * into the global application theme.
 *
 * Refs are forwarded to the underlying AntD Checkbox, preserving compatibility
 * with form libraries (react-hook-form, Formik), focus management, and any
 * existing ref usage in the consuming app.
 *
 * ─── Prop mapping ───────────────────────────────────────────────────────────
 *
 *   Pelagos prop    │ AntD equivalent   │ Notes
 *   ────────────────┼───────────────────┼────────────────────────────────────
 *   label           │ children          │ convenience alias; children wins
 *   checked         │ checked           │ controlled mode
 *   defaultChecked  │ defaultChecked    │ uncontrolled mode initial value
 *   disabled        │ disabled          │
 *   indeterminate   │ indeterminate     │ partial-selection dash marker
 *   onChange        │ onChange          │ (e: CheckboxChangeEvent) => void
 *   onBlur          │ onBlur            │
 *   onFocus         │ onFocus           │
 *
 * ─── AntD passthrough ───────────────────────────────────────────────────────
 *
 * All other Ant Design Checkbox props (classNames, styles, name, value, etc.)
 * pass through via ...rest unchanged:
 * https://ant.design/components/checkbox#api
 *
 * ─── Controlled vs uncontrolled ─────────────────────────────────────────────
 *
 * Controlled  → supply both `checked` and `onChange`.
 * Uncontrolled → supply `defaultChecked` only; AntD manages internal state.
 *
 * When used inside Ant Design Form.Item, set valuePropName="checked" on the
 * Form.Item wrapper:
 *
 *   <Form.Item name="agree" valuePropName="checked">
 *     <Checkbox label="I agree" />
 *   </Form.Item>
 *
 * ─── Design tokens ──────────────────────────────────────────────────────────
 *
 * Token overrides live in checkboxTheme.js. Colour is entirely AntD-driven;
 * Checkbox.layout.scss contains structural layout only.
 *
 * ─── Design reference ───────────────────────────────────────────────────────
 * /pages/prim-checkbox.html
 * Figma: https://www.figma.com/design/TOLfBpRePgynqwvDVp6fg3/Design-System?node-id=6715-2726
 */

// ─── ConfigProvider necessity ────────────────────────────────────────────────
//
// Checkbox always needs a local ConfigProvider — it applies colour and sizing
// overrides that are NOT in the PelagosProvider root token set:
//   · colorBgContainerDisabled (#f1f5f9)  — disabled surface colour
//   · colorTextDisabled        (#94a3b8)  — disabled text colour
//   · controlInteractiveSize   (16)       — checkbox box size
// Removing the ConfigProvider here would revert these to AntD defaults.

// ─── Component ───────────────────────────────────────────────────────────────

export const Checkbox = React.forwardRef(function Checkbox(
  {
    // ── Pelagos-specific props ───────────────────────────────────────────────
    label,                    // convenience label text; renders as AntD children

    // ── AntD Checkbox props (explicit for documentation + default values) ────
    checked,
    defaultChecked,
    disabled       = false,
    indeterminate  = false,
    onChange,
    onBlur,
    onFocus,
    children,                 // richer label content — takes priority over label
    className,

    // ── Passthrough ─────────────────────────────────────────────────────────
    ...rest                   // all other AntD Checkbox props: name, value, classNames, …
  },
  ref,
) {
  // ── Dev-mode prop guard ──────────────────────────────────────────────────
  if (process.env.NODE_ENV !== 'production' && label !== undefined && children !== undefined) {
    console.warn(
      '[PelagosCheckbox] Both `label` and `children` were provided. ' +
      '`children` takes priority; `label` will be ignored. Remove one of the two.',
    );
  }

  return (
    <ConfigProvider theme={getCheckboxTheme()}>
      <AntCheckbox
        ref={ref}
        checked={checked}
        defaultChecked={defaultChecked}
        disabled={disabled}
        indeterminate={indeterminate}
        onChange={onChange}
        onBlur={onBlur}
        onFocus={onFocus}
        className={className}
        data-state={disabled ? 'disabled' : 'default'}
        {...rest}
      >
        {children ?? label}
      </AntCheckbox>
    </ConfigProvider>
  );
});

Checkbox.displayName = 'PelagosCheckbox';

export default Checkbox;
