// geoserves-pelagos-design-system-main/components/primitives/menu/Menu.jsx
import React from 'react';
import { Menu as AntMenu, ConfigProvider } from 'antd';
import { getMenuTheme } from './menuTheme';
import './Menu.scss';

/**
 * Pelagos Menu — primitives/menu
 *
 * A thin Pelagos wrapper on top of Ant Design's Menu component.
 *
 * All interactive behaviours — keyboard navigation, submenu open/close,
 * selection, inline collapse, hover tooltips, and overflow handling — are
 * delegated entirely to AntD. Pelagos design tokens are injected via a
 * scoped ConfigProvider so they never bleed into the global application theme.
 *
 * Refs are forwarded to the underlying AntD Menu.
 *
 * ─── Prop mapping ───────────────────────────────────────────────────────────
 *
 *   Pelagos prop        │ AntD equivalent   │ Notes
 *   ────────────────────┼───────────────────┼──────────────────────────────
 *   mode                │ mode              │ 'horizontal' | 'vertical' | 'inline'
 *   theme               │ theme             │ 'light' | 'dark' — also selects Pelagos token set
 *   items               │ items             │ ItemType[] — declarative item tree
 *   selectedKeys        │ selectedKeys      │ controlled selected items
 *   defaultSelectedKeys │ defaultSelectedKeys│ uncontrolled initial selection
 *   openKeys            │ openKeys          │ controlled open submenus
 *   defaultOpenKeys     │ defaultOpenKeys   │ uncontrolled initial open submenus
 *   inlineCollapsed     │ inlineCollapsed   │ collapsed state (inline mode only)
 *   inlineIndent        │ inlineIndent      │ px per nesting level (default 24)
 *   multiple            │ multiple          │ allow multi-select
 *   selectable          │ selectable        │ allow item selection
 *   onClick             │ onClick           │ function({ key, keyPath, domEvent })
 *   onSelect            │ onSelect          │ function({ key, keyPath, selectedKeys })
 *   onDeselect          │ onDeselect        │ function({ key, keyPath, selectedKeys })
 *   onOpenChange        │ onOpenChange      │ function(openKeys: string[])
 *
 * ─── AntD passthrough ───────────────────────────────────────────────────────
 *
 * All other Ant Design Menu props (expandIcon, forceSubMenuRender,
 * overflowedIndicator, subMenuCloseDelay, subMenuOpenDelay, tooltip,
 * triggerSubMenuAction, popupRender, style, classNames, styles, etc.)
 * pass through via ...rest unchanged:
 * https://ant.design/components/menu#api
 *
 * ─── Items API ──────────────────────────────────────────────────────────────
 *
 * Items are passed as an `items` array of ItemType. Each item can be:
 *
 *   MenuItemType   — { key, label, icon?, disabled?, danger?, title? }
 *   SubMenuType    — { key, label, icon?, disabled?, children: ItemType[] }
 *   MenuItemGroup  — { type: 'group', label, children: MenuItemType[] }
 *   MenuDivider    — { type: 'divider', dashed? }
 *
 * ─── Design reference ───────────────────────────────────────────────────────
 * /pages/prim-menu.html
 */

// ─── Component ───────────────────────────────────────────────────────────────

export const Menu = React.forwardRef(function Menu(
  {
    // ── Pelagos-specific props ───────────────────────────────────────────────
    theme = 'light',   // 'light' | 'dark' — selects the Pelagos token set

    // ── Props forwarded directly to AntD Menu ───────────────────────────────
    mode                = 'vertical',
    items,
    selectedKeys,
    defaultSelectedKeys,
    openKeys,
    defaultOpenKeys,
    inlineCollapsed,
    inlineIndent,
    multiple            = false,
    selectable          = true,
    onClick,
    onSelect,
    onDeselect,
    onOpenChange,
    className,
    style,

    // ── Rest forwarded to AntD Menu ─────────────────────────────────────────
    ...rest
  },
  ref,
) {
  return (
    <ConfigProvider theme={getMenuTheme(theme)}>
      <AntMenu
        ref={ref}
        mode={mode}
        theme={theme}
        items={items}
        selectedKeys={selectedKeys}
        defaultSelectedKeys={defaultSelectedKeys}
        openKeys={openKeys}
        defaultOpenKeys={defaultOpenKeys}
        inlineCollapsed={inlineCollapsed}
        inlineIndent={inlineIndent}
        multiple={multiple}
        selectable={selectable}
        onClick={onClick}
        onSelect={onSelect}
        onDeselect={onDeselect}
        onOpenChange={onOpenChange}
        className={className}
        style={style}
        data-theme={theme}
        data-mode={mode}
        {...rest}
      />
    </ConfigProvider>
  );
});

Menu.displayName = 'PelagosMenu';

export default Menu;

// geoserves-pelagos-design-system-main/components/primitives/menu/Menu.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  OnChanges,
  SimpleChanges,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { NzMenuModule } from 'ng-zorro-antd/menu';
import { NzIconModule } from 'ng-zorro-antd/icon';
import { getMenuTheme } from './menuTheme';

/**
 * Pelagos Menu — Angular wrapper
 * primitives/menu/Menu.component.ts
 *
 * A thin Pelagos wrapper on top of ng-zorro-antd's nz-menu directive.
 * All interactive behaviours (keyboard navigation, submenu open/close,
 * inline collapse, selection, hover tooltips) are delegated to ng-zorro.
 * Pelagos design tokens are applied at module/bootstrap level via NZ_CONFIG.
 *
 * This is a standalone component (Angular 15+). NgModule apps should use
 * MenuModule instead, which re-exports MenuComponent for backward compat.
 *
 * ─── Input mapping ──────────────────────────────────────────────────────────
 *
 *   Pelagos @Input       │ ng-zorro equivalent   │ Notes
 *   ─────────────────────┼───────────────────────┼──────────────────────────
 *   mode                 │ nzMode                │ 'horizontal'|'vertical'|'inline'
 *   theme                │ nzTheme               │ 'light' | 'dark'
 *   inlineCollapsed      │ nzInlineCollapsed     │ collapse inline menu
 *   inlineIndent         │ nzInlineIndent        │ px per nesting level
 *   selectable           │ nzSelectable          │ allow item selection
 *   multiple             │ nzMultiple            │ allow multi-select
 *
 * ─── Items ──────────────────────────────────────────────────────────────────
 *
 * Unlike the React wrapper (which uses the `items` array API), the Angular
 * template uses ng-zorro directive markup. Consume the component via slot
 * projection — place `<gs-menu-item>`, `<gs-submenu>` etc. as children of
 * `<gs-menu>`, or use the template-driven approach documented in the README.
 *
 * ─── Design tokens ──────────────────────────────────────────────────────────
 *
 * Tokens come from menuTheme.js (shared with React). Inject them at the
 * module level using NZ_CONFIG or provide them via NzConfigService.
 *
 * ─── Design reference ───────────────────────────────────────────────────────
 * /pages/prim-menu.html
 */

// ─── Item type interfaces ─────────────────────────────────────────────────────

export interface PelagosMenuItemType {
  key:       string;
  label:     string;
  icon?:     string;
  disabled?: boolean;
  danger?:   boolean;
  title?:    string;
}

export interface PelagosSubMenuType {
  key:       string;
  label:     string;
  icon?:     string;
  disabled?: boolean;
  children:  PelagosItemType[];
}

export interface PelagosMenuGroupType {
  type:     'group';
  label:    string;
  children: PelagosMenuItemType[];
}

export interface PelagosMenuDividerType {
  type:   'divider';
  dashed?: boolean;
}

export type PelagosItemType =
  | PelagosMenuItemType
  | PelagosSubMenuType
  | PelagosMenuGroupType
  | PelagosMenuDividerType;

// ─── Component ───────────────────────────────────────────────────────────────

@Component({
  selector:     'gs-menu',
  standalone:   true,
  imports:      [CommonModule, NzMenuModule, NzIconModule],
  templateUrl:  './Menu.component.html',
  host:         { class: 'gs-menu-host' },
})
export class MenuComponent implements OnChanges {

  // ── Pelagos props ──────────────────────────────────────────────────────────

  /** Menu layout mode. Maps to ng-zorro nzMode. @default 'vertical' */
  @Input() mode: 'horizontal' | 'vertical' | 'inline' = 'vertical';

  /** Colour theme. Maps to ng-zorro nzTheme. Also selects the Pelagos token set. @default 'light' */
  @Input() theme: 'light' | 'dark' = 'light';

  /** Items array for declarative rendering. Mirrors the AntD items prop. */
  @Input() items: PelagosItemType[] = [];

  /** Controlled selected item keys. */
  @Input() selectedKeys: string[] = [];

  /** Controlled open submenu keys. */
  @Input() openKeys: string[] = [];

  /** Collapse inline menu. Maps to ng-zorro nzInlineCollapsed. */
  @Input() inlineCollapsed: boolean = false;

  /** Indentation in pixels per nesting level. Maps to ng-zorro nzInlineIndent. @default 24 */
  @Input() inlineIndent: number = 24;

  /** Allow selecting menu items. Maps to ng-zorro nzSelectable. @default true */
  @Input() selectable: boolean = true;

  /** Allow multi-selection. Maps to ng-zorro nzMultiple. @default false */
  @Input() multiple: boolean = false;

  // ── Events ────────────────────────────────────────────────────────────────

  /** Emits when a menu item is clicked. */
  @Output() itemClick = new EventEmitter<{ key: string; keyPath: string[] }>();

  /** Emits when a menu item is selected. */
  @Output() itemSelect = new EventEmitter<{ key: string; selectedKeys: string[] }>();

  /** Emits when a menu item is deselected (multiple mode). */
  @Output() itemDeselect = new EventEmitter<{ key: string; selectedKeys: string[] }>();

  /** Emits when open submenus change. */
  @Output() openChange = new EventEmitter<string[]>();

  // ── Derived ng-zorro binding values ──────────────────────────────────────

  nzMode:   'horizontal' | 'vertical' | 'inline' = 'vertical';
  nzTheme:  'light' | 'dark' = 'light';

  // ── Token theme (for documentation; injection handled at module level) ────
  get theme$() { return getMenuTheme(this.theme); }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['mode'])  { this.nzMode  = this.mode; }
    if (changes['theme']) { this.nzTheme = this.theme; }
  }

  // ── Type guards for template rendering ───────────────────────────────────

  isGroup(item: PelagosItemType): item is PelagosMenuGroupType {
    return (item as any).type === 'group';
  }

  isDivider(item: PelagosItemType): item is PelagosMenuDividerType {
    return (item as any).type === 'divider';
  }

  isSubMenu(item: PelagosItemType): item is PelagosSubMenuType {
    return !!(item as any).children && (item as any).type !== 'group';
  }

  isMenuItem(item: PelagosItemType): item is PelagosMenuItemType {
    return !(item as any).children && (item as any).type !== 'divider' && (item as any).type !== 'group';
  }

  // ── Event handlers ────────────────────────────────────────────────────────

  handleClick(key: string, keyPath: string[]): void {
    this.itemClick.emit({ key, keyPath });
  }

  handleSelect(key: string, selectedKeys: string[]): void {
    this.itemSelect.emit({ key, selectedKeys });
  }

  handleDeselect(key: string, selectedKeys: string[]): void {
    this.itemDeselect.emit({ key, selectedKeys });
  }

  handleOpenChange(openKeys: string[]): void {
    this.openChange.emit(openKeys);
  }
}

<!--
  Pelagos Menu — Angular template
  primitives/menu/Menu.component.html

  Delegates all rendering and behaviour to ng-zorro's nz-menu directive.
  Pelagos props are translated to ng-zorro bindings in MenuComponent.ts.

  The template renders the items array declaratively using structural
  directives. Each item type (menu item, submenu, group, divider) has its
  own ng-template for clear separation.

  For simple use cases, project content directly using <ng-content> —
  the component will wrap it in a `ul[nz-menu]` automatically.
-->

<ul
  nz-menu
  [nzMode]="nzMode"
  [nzTheme]="nzTheme"
  [nzInlineCollapsed]="inlineCollapsed"
  [nzInlineIndent]="inlineIndent"
  [nzSelectable]="selectable"
  [nzMultiple]="multiple"
  [attr.data-theme]="theme"
  [attr.data-mode]="mode"
>
  <!-- ── Items-array rendering ─────────────────────────────────────── -->
  <ng-container *ngIf="items && items.length > 0">
    <ng-container *ngFor="let item of items">

      <!-- Divider -->
      <li *ngIf="isDivider(item)" nz-menu-divider [nzDashed]="$any(item).dashed"></li>

      <!-- Group -->
      <li *ngIf="isGroup(item)" nz-menu-group [nzTitle]="$any(item).label">
        <ul>
          <li
            *ngFor="let child of $any(item).children"
            nz-menu-item
            [nzDisabled]="child.disabled"
            [nzDanger]="child.danger"
            [nzSelected]="selectedKeys?.includes(child.key)"
            (click)="handleClick(child.key, [child.key])"
          >
            <ng-container *ngIf="child.icon">
              <span nz-icon [nzType]="child.icon" nzTheme="outline"></span>
            </ng-container>
            <span>{{ child.label }}</span>
          </li>
        </ul>
      </li>

      <!-- SubMenu -->
      <li
        *ngIf="isSubMenu(item)"
        nz-submenu
        [nzTitle]="$any(item).label"
        [nzDisabled]="$any(item).disabled"
        [nzOpen]="openKeys?.includes($any(item).key)"
      >
        <ul>
          <ng-container *ngFor="let child of $any(item).children">
            <!-- Nested SubMenu -->
            <li
              *ngIf="isSubMenu(child)"
              nz-submenu
              [nzTitle]="$any(child).label"
              [nzDisabled]="$any(child).disabled"
            >
              <ul>
                <li
                  *ngFor="let grandchild of $any(child).children"
                  nz-menu-item
                  [nzDisabled]="grandchild.disabled"
                  [nzDanger]="grandchild.danger"
                  [nzSelected]="selectedKeys?.includes(grandchild.key)"
                  (click)="handleClick(grandchild.key, [grandchild.key, $any(child).key, $any(item).key])"
                >
                  <ng-container *ngIf="grandchild.icon">
                    <span nz-icon [nzType]="grandchild.icon" nzTheme="outline"></span>
                  </ng-container>
                  <span>{{ grandchild.label }}</span>
                </li>
              </ul>
            </li>

            <!-- Regular child item -->
            <li
              *ngIf="isMenuItem(child)"
              nz-menu-item
              [nzDisabled]="$any(child).disabled"
              [nzDanger]="$any(child).danger"
              [nzSelected]="selectedKeys?.includes($any(child).key)"
              (click)="handleClick($any(child).key, [$any(child).key, $any(item).key])"
            >
              <ng-container *ngIf="$any(child).icon">
                <span nz-icon [nzType]="$any(child).icon" nzTheme="outline"></span>
              </ng-container>
              <span>{{ $any(child).label }}</span>
            </li>
          </ng-container>
        </ul>
      </li>

      <!-- Plain menu item -->
      <li
        *ngIf="isMenuItem(item)"
        nz-menu-item
        [nzDisabled]="$any(item).disabled"
        [nzDanger]="$any(item).danger"
        [nzSelected]="selectedKeys?.includes($any(item).key)"
        [attr.title]="$any(item).title"
        (click)="handleClick($any(item).key, [$any(item).key])"
      >
        <ng-container *ngIf="$any(item).icon">
          <span nz-icon [nzType]="$any(item).icon" nzTheme="outline"></span>
        </ng-container>
        <span>{{ $any(item).label }}</span>
      </li>

    </ng-container>
  </ng-container>

  <!-- ── Slot projection (template-driven usage) ─────────────────── -->
  <ng-content></ng-content>
</ul>
